import { MarketplaceConfig } from './types';

export const MARKETPLACES: Record<string, MarketplaceConfig> = {
  'amazon.com': {
    id: 'amazon.com',
    name: 'United States',
    domain: 'amazon.com',
    country: 'US',
    currency: 'USD',
    currencySymbol: '$',
    language: 'en',
    flag: '🇺🇸',
    suggestionHost: 'completion.amazon.com',
  },
  'amazon.co.uk': {
    id: 'amazon.co.uk',
    name: 'United Kingdom',
    domain: 'amazon.co.uk',
    country: 'GB',
    currency: 'GBP',
    currencySymbol: '£',
    language: 'en',
    flag: '🇬🇧',
    suggestionHost: 'completion.amazon.co.uk',
  },
  'amazon.de': {
    id: 'amazon.de',
    name: 'Germany',
    domain: 'amazon.de',
    country: 'DE',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'de',
    flag: '🇩🇪',
    suggestionHost: 'completion.amazon.de',
  },
  'amazon.ca': {
    id: 'amazon.ca',
    name: 'Canada',
    domain: 'amazon.ca',
    country: 'CA',
    currency: 'CAD',
    currencySymbol: 'CA$',
    language: 'en',
    flag: '🇨🇦',
    suggestionHost: 'completion.amazon.ca',
  },
  'amazon.com.au': {
    id: 'amazon.com.au',
    name: 'Australia',
    domain: 'amazon.com.au',
    country: 'AU',
    currency: 'AUD',
    currencySymbol: 'AU$',
    language: 'en',
    flag: '🇦🇺',
    suggestionHost: 'completion.amazon.com.au',
  },
  'amazon.es': {
    id: 'amazon.es',
    name: 'Spain',
    domain: 'amazon.es',
    country: 'ES',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'es',
    flag: '🇪🇸',
    suggestionHost: 'completion.amazon.es',
  },
  'amazon.fr': {
    id: 'amazon.fr',
    name: 'France',
    domain: 'amazon.fr',
    country: 'FR',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'fr',
    flag: '🇫🇷',
    suggestionHost: 'completion.amazon.fr',
  },
  'amazon.it': {
    id: 'amazon.it',
    name: 'Italy',
    domain: 'amazon.it',
    country: 'IT',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'it',
    flag: '🇮🇹',
    suggestionHost: 'completion.amazon.it',
  },
  'amazon.co.jp': {
    id: 'amazon.co.jp',
    name: 'Japan',
    domain: 'amazon.co.jp',
    country: 'JP',
    currency: 'JPY',
    currencySymbol: '¥',
    language: 'ja',
    flag: '🇯🇵',
    suggestionHost: 'completion.amazon.co.jp',
  },
};

export const DEFAULT_MARKETPLACE = MARKETPLACES['amazon.com'];
